@SchoolPsychologicalHealthSupportSystem_GraphQL_API_HostAddress = http://localhost:5177

GET {{SchoolPsychologicalHealthSupportSystem_GraphQL_API_HostAddress}}/weatherforecast/
Accept: application/json

###
